
# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: 512

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: True
# used to set checkpoint path
# checkpoint: ''
checkpoint: '/home/linjiw/Documents/isaacgym_original/isaacgymenvs/outputs/2024-02-08/20-12-38/runs/Jackal/nn/Jackal.pth'
# checkpoint: '/home/linjiw/Documents/isaacgym_original/isaacgymenvs/outputs/2024-02-08/20-12-38/runs/Jackal/nn/last_Jackal_ep_2300_rew_21.13775.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal_original/isaacgymenvs/outputs/2024-02-02/15-25-12/runs/Jackal/nn/Jackal.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/outputs/2024-01-25/17-24-34/runs/Jackal/nn/last_Jackal_ep_4000_rew_26.76752.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/outputs/2024-01-25/17-24-34/runs/Jackal/nn/last_Jackal_ep_4500_rew_26.9162.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_850_rew_19.660906.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_3850_rew_24.529516.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_2850_rew_22.942776.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_1850_rew_23.049406.pth'
# checkpoint: '' #'/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_600_rew_18.842.pth'
# checkpoint: '/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_950_rew_18.482824.pth'
# set to True to use multi-gpu horovod training
multi_gpu: False

wandb_activate: True
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'isaacgymenvs'
capture_video: False
capture_video_freq: 1464
capture_video_len: 100
force_render: True

# disables rendering
headless: True

# set default task and default training config based on task
defaults:
  - task: Jackal
  - train: ${task}PPO
  - hydra/job_logging: disabled

# set the dire/home/linjiw/Downloads/newisaac/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_850_rew_19.660906.pth